global:
  scrape_interval: 15s

scrape_configs:
  - job_name: jaeger-spanmetrics
    static_configs:
      - targets: ["jaeger:8889"]

  - job_name: jaeger-internal
    static_configs:
      - targets: ["jaeger:8888"]
